# Model Validation - Cross Validation

In [4]:
from sklearn.datasets import load_iris
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [5]:
dataset = load_iris()
X = dataset['data']
y = dataset['target']

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3,random_state=4)

In [8]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train,y_train)
y_pred = knn.predict(X_test)
accuracy_score(y_test,y_pred)

0.9777777777777777

In [9]:
from sklearn.model_selection  import KFold

In [10]:
X = np.random.random(size=(25,5))
y = np.random.randint(low=0,high=2,size=25)

In [11]:
k_f = KFold(n_splits=6)
for train_index, test_index in k_f.split(X):
    print(train_index,test_index)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] [0 1 2 3 4]
[ 0  1  2  3  4  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24] [5 6 7 8]
[ 0  1  2  3  4  5  6  7  8 13 14 15 16 17 18 19 20 21 22 23 24] [ 9 10 11 12]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 17 18 19 20 21 22 23 24] [13 14 15 16]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 21 22 23 24] [17 18 19 20]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20] [21 22 23 24]


### cross_val_score

In [12]:
from sklearn.model_selection import cross_val_score


In [13]:
dataset = load_iris()
X = dataset['data']
y = dataset['target']

In [15]:
knn = KNeighborsClassifier(n_neighbors=5)
scores = cross_val_score(knn,X,y,cv=10,scoring='accuracy')
scores

array([1.        , 0.93333333, 1.        , 1.        , 0.86666667,
       0.93333333, 0.93333333, 1.        , 1.        , 1.        ])

In [16]:
scores.mean()

0.9666666666666668

### optimum for n_neighbours

In [17]:
for i in range(1,21):
    knn = KNeighborsClassifier(n_neighbors=i)
    scores = cross_val_score(knn,X,y,cv=10,scoring='accuracy')
    print(i,scores.mean())

1 0.96
2 0.9533333333333334
3 0.9666666666666666
4 0.9666666666666666
5 0.9666666666666668
6 0.9666666666666668
7 0.9666666666666668
8 0.9666666666666668
9 0.9733333333333334
10 0.9666666666666668
11 0.9666666666666668
12 0.9733333333333334
13 0.9800000000000001
14 0.9733333333333334
15 0.9733333333333334
16 0.9733333333333334
17 0.9733333333333334
18 0.9800000000000001
19 0.9733333333333334
20 0.9800000000000001


## for regression problem

In [22]:
try:
    from sklearn.datasets import load_boston
    from sklearn.linear_model import LinearRegression
    from sklearn.metrics import SCORERS
except:
    print("SOME ERROR")

SOME ERROR


In [ ]:
X,y = load_boston(return_X_y= True)

lr = LinearRegression(normalized=True)


In [ ]:
scores = cross_val_score(lr,X,y,cv=10,scoring='r2')
scores

In [21]:
scores.mean()

0.9800000000000001

In [23]:
list(SCORERS.key())

NameError: name 'SCORERS' is not defined