In [91]:
from sklearn.datasets import load_diabetes
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
import time

X,y = load_diabetes(return_X_y=True)

print(X.shape)
print(y.shape)

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

reg = LinearRegression()

reg.fit(X_train,y_train)

print("Coefficient : ",reg.coef_)
print("\nIntercept : ",reg.intercept_)

y_pred = reg.predict(X_test)
print(r2_score(y_test,y_pred))

print(X_train.shape)

(442, 10)
(442,)
Coefficient :  [  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]

Intercept :  151.88331005254167
0.4399338661568969
(353, 10)


In [92]:
import random
class MBGDRegressor:
    def __init__(self,batch_size,learning_rate=0.01,epochs=100):
        self.coef_=None
        self.intercept_=None
        self.lr= learning_rate
        self.epochs = epochs
        self.batch_size= batch_size

    def fit(self,X_train,y_train):
        #init the coeffiecients
        self.intercept_=0
        self.coef_ = np.ones(X_train.shape[1])

        for i in range(self.epochs):
            for j in range(int(X_train.shape[0]/self.batch_size)):
                idx = random.sample(range(X_train.shape[0]),self.batch_size)
            # update coef abd intercept
                y_hat = np.dot(X_train[idx],self.coef_)+self.intercept_
            #print("Shape if y_hat: ",y_hat.shape)
                intercept_der = -2*np.mean(y_train[idx]-y_hat)

                self.intercept_ = self.intercept_ - (self.lr* intercept_der)

                coef_der = -2 * np.dot((y_train[idx]-y_hat), X_train[idx])


                self.coef_ = self.coef_ - (self.lr*coef_der)

        print("Intercept : ",self.intercept_,"\n","Coefficient : ",self.coef_)
        

    def predict(self,X_test):
        return np.dot(X_test,self.coef_)+self.intercept_

In [93]:
mbgd = MBGDRegressor(batch_size=int(X_train.shape[0]/50),learning_rate=0.009,epochs=100)


In [94]:
mbgd.fit(X_train,y_train)

Intercept :  150.2954824612994 
 Coefficient :  [  40.03830826 -120.35650173  437.78865424  303.59034736  -13.80126768
  -74.93234427 -187.191702    115.63847773  389.99349537  109.82071758]


In [95]:
y_pred = mbgd.predict(X_test)

In [96]:
r2_score(y_test,y_pred)

0.4488599116343036

In [97]:
from sklearn.linear_model import SGDRegressor

In [98]:
sgd=SGDRegressor(learning_rate='constant',eta0=0.1)

In [99]:
batch_size=35
for i in range(100):
    idx = random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train[idx],y_train[idx])

In [100]:
sgd.coef_

array([  59.90587345,  -65.70478721,  343.28286773,  262.68876281,
         31.57707375,  -28.66546901, -148.61087579,  125.81453708,
        329.732155  ,  138.60866016])

In [101]:
sgd.intercept_


array([163.62156844])

In [102]:
sgd.predict(X_test)

array([168.84101638, 204.68821684, 151.1196437 , 122.22929028,
       257.07857649, 244.35283477, 120.5957287 , 125.59540315,
       106.06571719, 195.32881525, 174.8996098 , 182.63493101,
       194.34458879, 162.9050532 , 266.0965182 , 108.31414   ,
       196.32775435, 151.04322251, 152.36660839, 150.09886077,
       142.26840066, 202.97442951, 176.98609406, 191.57512039,
       140.36084647, 229.77632814, 207.25338827, 135.28737793,
        73.01499877, 254.72018289, 246.81818361, 131.3616702 ,
        84.95824528, 121.71463116, 212.61915479, 176.21369577,
       180.02400231, 207.88784817, 127.69996789, 247.12548797,
       146.41738393, 139.1574986 , 195.27524899, 197.73867943,
       180.54322976, 155.30326416, 185.17809483, 289.41701911,
       128.69584393, 201.82611085, 250.76170723, 138.78198372,
       153.71469321, 160.19441222, 202.40083364, 123.84411201,
       168.10047247,  99.32002169, 171.85064976, 153.09055227,
       176.06814911, 182.23916022, 123.98395894, 217.52

In [103]:
r2_score(y_test,y_pred)

0.4488599116343036